services:
  student-service:
    build:
      context: .
      dockerfile: Dockerfile.dev
      secrets:
        - maven_settings
    volumes:
      - .:/app
      - ./target:/app/target
    environment:
      - SPRING_PROFILES_ACTIVE=dev
      - SPRING_DEVTOOLS_RESTART_ENABLED=true
      - BLOB_STORAGE_CONTAINER_NAME=profile-pictures
      - BLOB_STORAGE_CONNECTION_STRING=UseDevelopmentStorage=true;DevelopmentStorageProxyUri=http://blob-storage:10000
      - SECURITY_JWT_SECRET_KEY=ODE2NTVkZDQ2ZGUzMWE4MzllY2ViZjI2OGUxZTBmMWNjMjk5NzRhNDM3NjVlZDZiZTU1ZDJlMWZjMzI2YWZlMQ==
      - TEACHME_COURSE_SERVICE_URL=http://course-service
      - SPRING_DATA_MONGODB_URI=mongodb://user:pass@db:27017
      - SPRING_DATA_MONGODB_DATABASE=students
      - GATEWAY_SERVER_URL=http://localhost:8888
      - KAFKA_CONFIG_BOOTSTRAP_SERVER=http://kafka-test:9092
    ports:
      - "8080:8080"
      - "35729:35729"
    depends_on:
      - mongo-db
      - redis-cache
    networks:
      - student-service-network

  mongo-db:
    image: mongodb/mongodb-community-server:6.0.12-ubi8
    container_name: db
    environment:
      - MONGO_INITDB_ROOT_USERNAME=user
      - MONGO_INITDB_ROOT_PASSWORD=pass
    ports:
      - "27017:27017"
    networks:
      - student-service-network

  redis-cache:
    image: redis/redis-stack-server:latest
    container_name: redis-cache
    ports:
      - "6379:6379"
    networks:
      - student-service-network

  azurite-blob-storage:
    container_name: blob-storage
    image: mcr.microsoft.com/azure-storage/azurite:3.33.0
    expose:
      - 10000
      - 10001
      - 10002
    ports:
      - "10000:10000"
      - "10001:10001"
      - "10002:10002"
    volumes:
      - blob-storage-volume:/data mcr.microsoft.com/azure-storage/azurite
    networks:
      - student-service-network

  zookeeper:
    image: confluentinc/cp-zookeeper:7.4.4
    environment:
      ZOOKEEPER_CLIENT_PORT: 2181
      ZOOKEEPER_TICK_TIME: 2000
    ports:
      - "22181:2181"
    networks:
      - student-service-network

  kafka:
    image: confluentinc/cp-kafka:7.4.4
    container_name: kafka-test
    depends_on:
      - zookeeper
    ports:
      - "29092:29092"
    environment:
      KAFKA_BROKER_ID: 1
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://kafka-test:9092,PLAINTEXT_HOST://localhost:29092
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: PLAINTEXT:PLAINTEXT,PLAINTEXT_HOST:PLAINTEXT
      KAFKA_INTER_BROKER_LISTENER_NAME: PLAINTEXT
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1
    networks:
      - student-service-network

volumes:
  blob-storage-volume:

secrets:
  maven_settings:
    file: ~/.m2/settings.xml

networks:
  student-service-network:
    driver: bridge