services:
  mongo-db:
    image: mongodb/mongodb-community-server
    container_name: db
    environment:
      - MONGO_INITDB_ROOT_USERNAME=user
      - MONGO_INITDB_ROOT_PASSWORD=pass
    ports:
      - "27017:27017"