services:
  student-service:
    build: .
    networks:
      - student-service-network
    environment:
      - SPRING_PROFILES_ACTIVE=prod
    ports:
      - "8080:8080"

networks:
  student-service-network:
