# MongoDB
spring.data.mongodb.uri=mongodb://user:pass@mongo-db:27017
spring.data.mongodb.database=students

# Redis
spring.data.redis.host=redis-cache
teachme.cache.enabled=true

# JWT auth
jwt.public-key-path=classpath:auth/public-key.pem
jwt.protected-paths=/api/students/**
